from src.curator.sources.aggregators import (
    ArxivFetcher,
    GitHubTrendingFetcher,
    HackerNewsFetcher,
    InfoQFetcher,
    LobstersFetcher,
    RedditFetcher,
    fetch_arxiv,
    fetch_github_trending,
    fetch_hacker_news,
    fetch_infoq,
    fetch_lobsters,
    fetch_reddit,
)
from src.curator.sources.blogs import (
    BLOG_FETCHERS,
    fetch_airbnb_engineering,
    fetch_atlassian_engineering,
    fetch_cloudflare_blog,
    fetch_dropbox_tech,
    fetch_etsy_craft,
    fetch_figma_tech,
    fetch_github_engineering,
    fetch_google_developers,
    fetch_meta_engineering,
    fetch_microsoft_engineering,
    fetch_netflix_tech,
    fetch_pinterest_engineering,
    fetch_shopify_blog,
    fetch_slack_engineering,
    fetch_spotify_engineering,
    fetch_square_corner,
    fetch_stackoverflow_engineering,
    fetch_stripe_blog,
)
from src.curator.sources.custom import (
    LinkedInEngineeringFetcher,
    UberEngineeringFetcher,
    fetch_linkedin_engineering,
    fetch_uber_engineering,
)

__all__ = [
    # Aggregators
    "HackerNewsFetcher",
    "GitHubTrendingFetcher",
    "ArxivFetcher",
    "RedditFetcher",
    "LobstersFetcher",
    "InfoQFetcher",
    "fetch_hacker_news",
    "fetch_github_trending",
    "fetch_arxiv",
    "fetch_reddit",
    "fetch_lobsters",
    "fetch_infoq",
    # Blogs
    "BLOG_FETCHERS",
    "fetch_netflix_tech",
    "fetch_shopify_blog",
    "fetch_cloudflare_blog",
    "fetch_stripe_blog",
    "fetch_meta_engineering",
    "fetch_airbnb_engineering",
    "fetch_github_engineering",
    "fetch_dropbox_tech",
    "fetch_atlassian_engineering",
    "fetch_slack_engineering",
    "fetch_spotify_engineering",
    "fetch_pinterest_engineering",
    "fetch_google_developers",
    "fetch_microsoft_engineering",
    "fetch_etsy_craft",
    "fetch_square_corner",
    "fetch_figma_tech",
    "fetch_stackoverflow_engineering",
    # Custom
    "UberEngineeringFetcher",
    "LinkedInEngineeringFetcher",
    "fetch_uber_engineering",
    "fetch_linkedin_engineering",
]
