from typing import Dict, Optional

# Declarative configurations for RSS/Atom-based feeds
FEED_CONFIGS: Dict[str, str] = {
    "infoq": "https://feed.infoq.com/",
    "netflix_tech": "https://netflixtechblog.com/feed",
    "shopify_blog": "https://shopify.engineering/blog.atom",
    "cloudflare_blog": "https://blog.cloudflare.com/rss/",
    "stripe_blog": "https://stripe.com/blog/feed.rss",
    "meta_engineering": "https://engineering.fb.com/feed/",
    "airbnb_engineering": "https://medium.com/feed/airbnb-engineering",
    "github_engineering": "https://github.blog/category/engineering/feed/",
    "dropbox_tech": "https://dropbox.tech/feed",
    "atlassian_engineering": "https://atlassianblog.wpengine.com/feed/",
    "slack_engineering": "https://slack.engineering/feed/",
    "spotify_engineering": "https://engineering.atspotify.com/feed/",
    "pinterest_engineering": "https://medium.com/feed/pinterest-engineering",
    "google_developers": "https://blog.google/technology/developers/rss/",
    "microsoft_engineering": "https://devblogs.microsoft.com/engineering-at-microsoft/feed/",
    "etsy_craft": "https://codeascraft.com/feed/",
    "square_corner": "https://developer.squareup.com/blog/rss.xml",
    "figma_tech": "https://www.figma.com/blog/feed/atom.xml",
    "stackoverflow_engineering": "https://stackoverflow.blog/engineering/feed/",
}

# User aliases mapped to canonical source identifiers
SOURCE_ALIASES: Dict[str, str] = {
    # Aggregators
    "hn": "hacker_news",
    "hackernews": "hacker_news",
    "hacker_news": "hacker_news",
    "github": "github_trending",
    "gh": "github_trending",
    "trending": "github_trending",
    "github_trending": "github_trending",
    "arxiv": "arxiv",
    "papers": "arxiv",
    "reddit": "reddit",
    "lobsters": "lobsters",
    "infoq": "infoq",
    # Engineering Blogs
    "netflix": "netflix_tech",
    "netflix_tech": "netflix_tech",
    "netflix_blog": "netflix_tech",
    "cloudflare": "cloudflare_blog",
    "cloudflare_blog": "cloudflare_blog",
    "cf": "cloudflare_blog",
    "stripe": "stripe_blog",
    "stripe_blog": "stripe_blog",
    "stripe_engineering": "stripe_blog",
    "shopify": "shopify_blog",
    "shopify_blog": "shopify_blog",
    "shopify_engineering": "shopify_blog",
    "meta": "meta_engineering",
    "meta_engineering": "meta_engineering",
    "facebook": "meta_engineering",
    "facebook_engineering": "meta_engineering",
    "fb": "meta_engineering",
    "fb_engineering": "meta_engineering",
    "uber": "uber_engineering",
    "uber_engineering": "uber_engineering",
    "uber_blog": "uber_engineering",
    "airbnb": "airbnb_engineering",
    "airbnb_engineering": "airbnb_engineering",
    "airbnb_data": "airbnb_engineering",
    "github_engineering": "github_engineering",
    "github_blog": "github_engineering",
    "gh_engineering": "github_engineering",
    "dropbox": "dropbox_tech",
    "dropbox_tech": "dropbox_tech",
    "dropbox_engineering": "dropbox_tech",
    "atlassian": "atlassian_engineering",
    "atlassian_engineering": "atlassian_engineering",
    "slack": "slack_engineering",
    "slack_engineering": "slack_engineering",
    "spotify": "spotify_engineering",
    "spotify_engineering": "spotify_engineering",
    "spotify_labs": "spotify_engineering",
    "linkedin": "linkedin_engineering",
    "linkedin_engineering": "linkedin_engineering",
    "pinterest": "pinterest_engineering",
    "pinterest_engineering": "pinterest_engineering",
    "google": "google_developers",
    "google_dev": "google_developers",
    "google_developers": "google_developers",
    "google_blog": "google_developers",
    "microsoft": "microsoft_engineering",
    "microsoft_engineering": "microsoft_engineering",
    "msft": "microsoft_engineering",
    "msft_engineering": "microsoft_engineering",
    "etsy": "etsy_craft",
    "etsy_craft": "etsy_craft",
    "code_as_craft": "etsy_craft",
    "etsy_code_as_craft": "etsy_craft",
    "square": "square_corner",
    "square_corner": "square_corner",
    "square_corner_blog": "square_corner",
    "square_engineering": "square_corner",
    "block": "square_corner",
    "figma": "figma_tech",
    "figma_tech": "figma_tech",
    "figma_engineering": "figma_tech",
    "figma_blog": "figma_tech",
    "stackoverflow": "stackoverflow_engineering",
    "stackoverflow_engineering": "stackoverflow_engineering",
    "so": "stackoverflow_engineering",
    "so_engineering": "stackoverflow_engineering",
}

# Human-friendly publication display names for Telegram and help menus
SOURCE_DISPLAY_NAMES: Dict[str, str] = {
    "hacker_news": "Hacker News",
    "github_trending": "GitHub Trending",
    "arxiv": "ArXiv Papers",
    "reddit": "Reddit",
    "lobsters": "Lobsters",
    "infoq": "InfoQ",
    "netflix_tech": "Netflix TechBlog",
    "shopify_blog": "Shopify Engineering",
    "cloudflare_blog": "Cloudflare Blog",
    "stripe_blog": "Stripe Engineering",
    "meta_engineering": "Meta Engineering",
    "uber_engineering": "Uber Engineering",
    "airbnb_engineering": "Airbnb Engineering",
    "github_engineering": "GitHub Engineering",
    "dropbox_tech": "Dropbox Tech Blog",
    "atlassian_engineering": "Atlassian Engineering",
    "slack_engineering": "Slack Engineering",
    "spotify_engineering": "Spotify Engineering",
    "linkedin_engineering": "LinkedIn Engineering",
    "pinterest_engineering": "Pinterest Engineering",
    "google_developers": "Google Developers",
    "microsoft_engineering": "Microsoft Engineering",
    "etsy_craft": "Etsy Code as Craft",
    "square_corner": "Square Corner Blog",
    "figma_tech": "Figma Tech Blog",
    "stackoverflow_engineering": "Stack Overflow Engineering",
}

# Concise category badges displayed on Playwright social graphics cards
SOURCE_CATEGORY_MAP: Dict[str, str] = {
    "arxiv": "Arxiv",
    "hacker_news": "Hacker News",
    "github_trending": "GitHub Trending",
    "reddit": "Reddit",
    "lobsters": "Lobsters",
    "infoq": "InfoQ",
    "netflix_tech": "Netflix Tech",
    "shopify_blog": "Shopify Engineering",
    "cloudflare_blog": "Cloudflare",
    "stripe_blog": "Stripe Engineering",
    "meta_engineering": "Meta Engineering",
    "uber_engineering": "Uber Engineering",
    "airbnb_engineering": "Airbnb Engineering",
    "github_engineering": "GitHub Engineering",
    "dropbox_tech": "Dropbox Tech",
    "atlassian_engineering": "Atlassian Engineering",
    "slack_engineering": "Slack Engineering",
    "spotify_engineering": "Spotify Engineering",
    "linkedin_engineering": "LinkedIn Engineering",
    "pinterest_engineering": "Pinterest Engineering",
    "google_developers": "Google Developers",
    "microsoft_engineering": "Microsoft Engineering",
    "etsy_craft": "Etsy Code as Craft",
    "square_corner": "Square Corner Blog",
    "figma_tech": "Figma Tech",
    "stackoverflow_engineering": "Stack Overflow",
}


def resolve_source(source_name: str) -> Optional[str]:
    """Resolves a user-provided source name or alias to its canonical source identifier."""
    if not source_name:
        return None
    normalized = source_name.strip().lower().replace("-", "_").replace(" ", "_")
    return SOURCE_ALIASES.get(normalized)
